CREATE TABLE school.FACULTY (
FacultyID INT NOT NULL,
FacultyName VARCHAR(25),
PRIMARY KEY (FacultyID));
CREATE TABLE school.STUDENT (
StudentID INT NOT NULL,
StudentName VARCHAR(25),
PRIMARY KEY (StudentID));
CREATE TABLE school.COURSE (
CourseID VARCHAR(8) NOT NULL,
CourseName VARCHAR(15),
PRIMARY KEY (CourseID));
CREATE TABLE school.QUALIFIED (
FacultyID INT NOT NULL,
CourseID VARCHAR(8) NOT NULL,
DateQualified DATE,
PRIMARY KEY (FacultyID, CourseID),
FOREIGN KEY (FacultyID) REFERENCES FACULTY (FacultyID),
FOREIGN KEY (CourseID) REFERENCES COURSE (CourseID));
CREATE TABLE school.SECTION (
SectionNo INT NOT NULL,
Semester VARCHAR(7) NOT NULL,
CourseID VARCHAR(8) NOT NULL,
PRIMARY KEY (SectionNo, Semester, CourseID),
FOREIGN KEY (CourseID) REFERENCES COURSE (CourseID));
CREATE TABLE school.REGISTRATION (
StudentID INT NOT NULL,
SectionNo INT NOT NULL,
Semester VARCHAR(7) NOT NULL,
PRIMARY KEY (StudentID, SectionNo, Semester),
FOREIGN KEY (StudentID) REFERENCES STUDENT (StudentID),
FOREIGN KEY (SectionNo, Semester) REFERENCES SECTION (SectionNo, Semester));